# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xASkrBdbB4uFzMy1xJngOwYuP4hwkQWC
"""

import kagglehub

# Download latest version
path = kagglehub.model_download("davidtroxellucla/pygem-using-googles-gemma-for-a-python-chatbot/keras/pygem-original")

print("Path to model files:", path)